Rack app WhatTime?
skvortsovvg/GetTime pull request #2
Opened 2022-08-03 17:10 UTC by skvortsovvg

2022-08-04 08:10 UTC, BubuntuClu requested changes

2022-08-04 08:10 UTC, BubuntuClu commented on timer.rb
> +class App
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2022-08-04 08:10 UTC, BubuntuClu commented on timer.rb
> +    return [
сделай метод, который отдает ответ, типа `error_result` только общего для всех ответов. в нем используй `Rack::Response`

2022-08-04 08:10 UTC, BubuntuClu commented on timer.rb
> +    result << DATE.select { |key, value| params.include?(key) }.values.join("-")
зачем две константы, а не одна?

2022-08-04 08:10 UTC, BubuntuClu commented on timer.rb
> +    return error_result unless env['PATH_INFO'].include?('/time')
замени на `if`

2022-08-04 08:10 UTC, BubuntuClu commented on timer.rb
> +    unknown = params.select { |key| !(TIME.keys.include?(key) || DATE.keys.include?(key)) }
ты тут делаешь перебор параметров, и потом еще на 43 строке делаешь тоже самое, не оптимально. получи нажнуе данные за один обход параметров

2022-08-04 10:52 UTC, skvortsovvg commented on timer.rb
> +    return [
+

2022-08-04 10:53 UTC, skvortsovvg commented on timer.rb
> +class App
+

2022-08-04 10:53 UTC, skvortsovvg commented on timer.rb
> +    result << DATE.select { |key, value| params.include?(key) }.values.join("-")
одна форматрирует время, другая дату

2022-08-04 10:54 UTC, skvortsovvg commented on timer.rb
> +    return error_result unless env['PATH_INFO'].include?('/time')
почему здесь лучше if not? rubocop ругается на такое

2022-08-04 10:58 UTC, skvortsovvg commented on timer.rb
> +    unknown = params.select { |key| !(TIME.keys.include?(key) || DATE.keys.include?(key)) }
переделал всё согласно замечаниям, может уже не актуально

2022-08-04 17:06 UTC, BubuntuClu commented on timer.rb
> +    return error_result unless env['PATH_INFO'].include?('/time')
ты можешь написать `if .exclude?`

2022-08-04 17:13 UTC, BubuntuClu requested changes

2022-08-04 17:13 UTC, BubuntuClu commented on time_formatter.rb
> +  DATE = { year: "%Y", month: "%m", day: "%d" }
>одна форматрирует время, другая дату

это понятно, а зачем разбивать на две константы? почему не сделать общую? 
ты даже метод сделал, чтобы собрать ключи в одном месте `valid_params`

2022-08-04 17:13 UTC, BubuntuClu commented on timer.rb
> +    unknown = params.select { |key| !TimeFormatter.valid_params.include?(key) }
>может уже не актуально

актуально. тут перебор всех параметров, и потом внутри методов `get_date/get_time`

2022-08-04 17:13 UTC, BubuntuClu commented on time_formatter.rb
> +  def self.get_date(params)
если все методы `self`, стоит тогда обернуть в `class << self`

2022-08-04 17:13 UTC, BubuntuClu commented on timer.rb
> +    unknown = params.select { |key| !TimeFormatter.valid_params.include?(key) }
вообще странное использование класса. сделай из него полноценный сервис.

передал в него параметры. распарсил. узнал как распарсил. вызвал нужный метод.
`new/call/success?/time_string/invalid_string` такие методы он может в себе содержать

2022-08-05 07:37 UTC, skvortsovvg commented on time_formatter.rb
> +  def self.get_date(params)
+

2022-08-05 07:50 UTC, skvortsovvg commented on timer.rb
> +    return error_result unless env['PATH_INFO'].include?('/time')
У меня нет такого метода. Насколько понял раньше он был в Rails по умолчанию, сейчас для этого нужно дополнительно подключать расширение 'active_support/core_ext/enumerable'. Посмотрел в документации: exclude? делает банально !Include?, поэтому не вижу смысла переделывать.

2022-08-05 08:08 UTC, skvortsovvg commented on time_formatter.rb
> +  DATE = { year: "%Y", month: "%m", day: "%d" }
У нас может быть запрошены дата, время или сразу всё. Дата форматируется так "2000-01-01". Время так "23:59:59". Если всё вместе между ними должен быть пробел "2000-01-01 23:59:59". При этом любого из параметра может не быть, может быть например так "2000-01 23:59". Соответственно такая реализация решает это всё просто и как мне кажется более-менее логично.

2022-08-05 08:08 UTC, skvortsovvg commented on time_formatter.rb
> +  def self.get_date(params)
+

2022-08-05 08:13 UTC, skvortsovvg commented on timer.rb
> +    unknown = params.select { |key| !TimeFormatter.valid_params.include?(key) }
Там разные данные перебираются. В первом цикле мы смотрим параметры из запроса, во втором уже параметры-константы, которые понимает сервис. Важно отличие в том, что по условию задачи порядок параметров не важен, а в ответе понятное дело результат должен быть отформатированного вида. Такой подход как раз и решает эту задачу.

2022-08-05 09:04 UTC, skvortsovvg commented on timer.rb
> +    unknown = params.select { |key| !TimeFormatter.valid_params.include?(key) }
Я не понимаю зачем так заморачиваться, выносить в отдельный сервис. У нас Аpp это и есть этот сервис, который должен обработать входящие данные и отдать ответ. Я понимаю твое первое замечание про разеделение логики, но  вот на счет сервиса мне не понятно. Получается я просто туда всё вынесу, всё всё. А в App буду просто делать типа return TimeFormatter.new(query). Для меня загадка, почему такую простую функцию нельзя реализовать просто в самом классе App.

2022-08-05 10:20 UTC, skvortsovvg commented on timer.rb
> +    unknown = params.select { |key| !TimeFormatter.valid_params.include?(key) }
итого, переделал теперь так, посмотри

2022-08-05 18:44 UTC, BubuntuClu commented on timer.rb
> +    unknown = params.select { |key| !TimeFormatter.valid_params.include?(key) }
чтобы ты мог скопировать свой класс в другое приложение и у тебя не было никакой зависимости от логики текущего кода. просто класс, который парсит параметры.

2022-08-05 18:46 UTC, BubuntuClu commented on timer.rb
> +    return error_result unless env['PATH_INFO'].include?('/time')
таким образом ты избавляешь от `unless`

2022-08-05 18:47 UTC, BubuntuClu commented on time_formatter.rb
> +  DATE = { year: "%Y", month: "%m", day: "%d" }
из-за этого ты два раза гоняешь дорогую операцию `Time.strftime, хотя про порядок и разбивание в ТЗ ничего не говорилось. что запросил то и получаешь

2022-08-05 18:49 UTC, BubuntuClu requested changes

2022-08-05 18:49 UTC, BubuntuClu commented on time_formatter.rb
> +      @status = 404
этот класс ничего про статусы не должен знать. за ответ у тебя отвечает `app`, какие отдать статусы, какие отдать заголовки и что в `body`написать отвечает `app`. данный класс только парсит строку с параметрами. если распарсил, может отдать время. если ошибки, то отдает ошибки.

>Получается я просто туда всё вынесу, всё всё. А в App буду просто делать типа return TimeFormatter.new(query).

это неправильный вывод. отсюда и неправильная реализация

2022-08-05 18:52 UTC, BubuntuClu commented on timer.rb
> +    unknown = params.select { |key| !TimeFormatter.valid_params.include?(key) }
вспомни как у тебя был реализован GistService. тут практически тоже самое

2022-08-05 19:03 UTC, BubuntuClu commented on time_formatter.rb
> +  def parse_validate()
скобки не пишутся у методов без параметров

2022-08-05 19:03 UTC, BubuntuClu commented on time_formatter.rb
> +  DATE = { year: "%Y", month: "%m", day: "%d" }
в теории могу согласиться с тобой, но ты все равно два раза гоняешь параметры. сначала чтобы проверить что ошибок нет, а потом каждый тип константы на включение ее ключей в значения в параметрах. это плохо для производительности. представь тысячи/миллоны значений в массиве. и будут они дважды перебираться

2022-08-08 17:06 UTC, BubuntuClu commented on time_formatter.rb
> +    validate
из инициализации не вызывают логику. для этого есть метод `call`

2022-08-08 17:06 UTC, BubuntuClu commented on time_formatter.rb
> +    unknown = @params.select { |key| !valid_params.include?(key) }
ты упорно не убираешь двойной перебор параметров.

```
params.each do |param|
  if valid_params[param]
      valid << valid_params[param]
  else
      invalid << param
  end
end
```

таким образом у тебя за один обход собираются два массива, которые ты потом обрабатываешь как тебе надо.

у тебя сейчас параметры сначала итерируются в методе `validate`, а потом в каждом из методов `get_date/get_time`

2022-08-08 20:59 UTC, skvortsovvg commented on time_formatter.rb
> +    unknown = @params.select { |key| !valid_params.include?(key) }
Там есть разница, вот смотри... Первый раз я обхожу полученные параметры, а второй раз я обхожу уже внутренние хэши-константы. Т.е. я перебираю не миллион параметров (гипотетически переданных в запросе), а фиксированное число тех, которые сервис понимает. 

И потом, если сделать как в твоем примере, то мы решаем проблему с двойным перебором. Но тогда придется решать другую проблему - сортировку параметров. Т.е. предположим что параметры переданы в неправильном порядке, например, day%2Cyear%2Csecond%2Chour%2Cmonth%2Cminute. По условию это не должно влиять на корректность результата. Придется делать дополнительные действия после разделения параметров на массивы. Что убивает весь эффект оптимизации от одиночного перебора.

Ну, мне так кажется...

2022-08-16 10:26 UTC, merged